### ISSUE TITLE
[feature] Need mergify bot configuration

### ISSUE THREAD

**Issue by congqixia** [milvus-io/milvus-proto#2]
`milvus-proto` project needs mergify bot configured to make standard github workflow work

**Comment by jennyli-z** [comment]
1. Please define when we can add `ci-passed` label for this project @congqixia

**Comment by jennyli-z** [comment]
2. Also please add https://github.com/milvus-io/milvus-proto/blob/master/OWNERS that can approve the pr

**Comment by congqixia** [comment]
> 1. Please define when we can add `ci-passed` label for this project @congqixia

since we only provide protobuf files here, the only thing need to check is the proto format

**Comment by congqixia** [comment]
> 2. Also please add https://github.com/milvus-io/milvus-proto/blob/master/OWNERS that can approve the pr

@yhmo
