### ISSUE TITLE
[feature] Need a @sre-ci-robot to auto merge PRs

### ISSUE THREAD

**Issue by XuanYang-cn** [milvus-io/milvus-proto#3]

**Comment by jennyli-z** [comment]
https://prow.zilliz.cc/tide tide config updated 
![image](https://user-images.githubusercontent.com/93511422/158297776-e03e4d3d-9031-4a7d-8004-4dd281eb195a.png)

**Comment by jennyli-z** [comment]
![image](https://user-images.githubusercontent.com/93511422/158305389-91f28ef6-9ac8-45e4-ba6b-ba8168552c81.png)
Done by config the prow.
Please check @XuanYang-cn
